- name: Generate redirect config
  template:
    src: redirect.conf
    dest: /etc/nginx/sites-enabled/redirect.conf
    owner: www-data
    group: www-data
  when: "{{ nginx_redirects }}"
  notify: nginx restart
